### ISSUE TITLE
Link from Form to Class type in Salesforce

### ISSUE THREAD

**Issue by emmaclarkefestinalente** [KeithClarke/FestinaLente#27] opened 2016-04-07 13:06 UTC
Hi Keith

Is is possible to link from the main class type field in the forms (Lesson, camp or session the applicant wishes to participate in) to the Class Type in Salesforce?

many thanks
Emma

**Comment by KeithClarke** [comment] 2016-04-11 18:09
This looks like a duplicate of #28. If it isn'r re-open it.

**Closed by KeithClarke** 2016-04-11 18:09 UTC
